config/routes.rb
TestService::Application.routes.draw do
  get 'tidepool_identities/new'

  root to: 'landing_page#show'

  match '/dash', to: 'dashboard#show'
  match '/start/:def_id', to: 'assessment_start#new', as: 'start'
  match '/show', to: 'assessment_start#show', as: 'show'
  
  match '/login', to: 'sessions#new', :as => 'login'
  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure'
  match '/logout', to: 'sessions#destroy', :as => 'logout'
  

  scope 'api/v1' do
    resources :assessments
    resources :profiles
    resources :user_events
  end

end

app/models/adjective_circle.rb
class AdjectiveCircle < ActiveRecord::Base
  attr_accessible :distance_mean, :distance_sd, :distance_weight, :maps_to, :name_pair, :overlap_mean, :overlap_sd, :overlap_weight, :size_mean, :size_sd, :size_weight, :version
end

app/models/assessment.rb
# == Schema Information
#
# Table name: assessments
#
#  id         :integer          not null, primary key
#  definition :string(255)
#  date_taken :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Assessment < ActiveRecord::Base
  serialize :event_log, JSON
  serialize :intermediate_results, JSON
  serialize :stages, JSON
  serialize :aggregate_results, JSON

  attr_accessible :date_taken, :score, :stages, :event_log, :intermediate_results, :stage_completed,
                  :aggregate_results, :results_ready, :big5_dimension, :holland6_dimension, :emo8_dimension
  belongs_to :definition
  belongs_to :user
  belongs_to :profile_description

  def self.create_with_definition_and_user(definition, user)
    create! do |assessment|
      assessment.definition = definition
      assessment.stages = definition.stages_from_stage_definition
      assessment.user = user
      assessment.date_taken = DateTime.now
      assessment.results_ready = false
      assessment.stage_completed = -1
    end
  end

end

app/models/definition.rb
Dir[File.expand_path('../generators/*.rb', __FILE__)].each {|file| require file }

class Definition < ActiveRecord::Base
  serialize :stages, JSON
  attr_accessible :name, :stages, :instructions, :end_remarks, :experiment, :icon

  def self.find_or_return_default(def_id)
    begin
      definition = self.find(def_id)
    rescue ActiveRecord::RecordNotFound
      definition = self.first
    end
    definition
  end

  def stages_from_stage_definition
    result = []
    self.stages.each do |stage|
      module_name = stage['view_name']
      klass_name = "#{module_name.camelize}Generator"
      generator = klass_name.constantize.new(stage)
      result << generator.generate
    end  
    result
  end
end

app/models/element.rb
class Element < ActiveRecord::Base
  attr_accessible :mean, :name, :standard_deviation, :version, :weight_agreeableness, :weight_conscientiousness, :weight_extraversion, :weight_neuroticism, :weight_openness
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  attr_accessible :provider, :uid, :user_id
  belongs_to :user

  def self.find_or_create_with_omniauth(auth)
    identity = find_by_provider_and_uid(auth['provider'], auth['uid'])
    if identity.nil?
      identity = create_with_omniauth(auth)
    end
    identity
  end

  def self.create_with_omniauth(auth)
    create! do |identity|
      identity.uid = auth['uid']
      identity.provider = auth['provider']
    end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :elements, :name, :primary_color
end

app/models/profile_description.rb
class ProfileDescription < ActiveRecord::Base
  attr_accessible :big5_dimension, :bullet_description, :code, :description, :holland6_dimension, :name, :one_liner, :logo_url

  serialize :description, JSON
  serialize :bullet_description, JSON

  has_many :users
end

app/models/record_event.rb
module RecordEvent
	ACTION_EVENT_QUEUE = 'action_events'

	def record
		case @event_type.to_i
		when UserEvent::ANALYSIS_EVENT
			save_in_store
		when UserEvent::ACTION_EVENT
			publish_to_queue
		else
			# logger.info("Unknown Event Type: #{self.event_data}")
		end
	end

	private

	def save_in_store
		$redis.rpush(key, @event_data.to_json)
	end

	def publish_to_queue
		$redis.publish(ACTION_EVENT_QUEUE, @event_data.to_json)
	end

	def key
		"user:#{self.user_id}:test:#{self.assessment_id}"
	end
end

app/models/tidepool_identity.rb
class TidepoolIdentity < OmniAuth::Identity::Models::ActiveRecord
  attr_accessible :name, :email, :guest, :gender, :password_digest, :password, :password_confirmation
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :guest, :gender

  has_many :assessments
  has_many :identities
  belongs_to :profile_description

  def self.create_guest
    guest_id = rand(36**10).to_s(36)

    # Create the user as a guest
    user = User.create!(guest: true, name: "User_#{guest_id}")

    # Create an guest identity for the user
    identity = Identity.create(provider: 'guest', uid: guest_id)
    identity.user = user
    identity.save!

    user
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.guest = false
      user.name = auth['info']['name']
      user.email = auth['info']['email']
      user.gender = auth['info']['gender']
    end
  end

  def update_with_omniauth(auth)
    self.guest = false
    self.name = auth['info']['name']
    self.email = auth['info']['email']
    self.gender = auth['info']['gender']
    self.save!
  end
end

app/models/user_event.rb
class UserEvent
	include RecordEvent
	extend ActiveModel::Naming
	include ActiveModel::Conversion
	def persisted?	
  	false
	end
	
	attr_accessor :user_id, :assessment_id, :event_type

	ANALYSIS_EVENT = 0
	ACTION_EVENT = 1

	def initialize(data)
		@user_id = data[:user_id]
		@assessment_id = data[:assessment_id]
		@event_type = data[:event_type]
		raise ArgumentError("Invalid Event #{data}") if @user_id.nil? || @assessment_id.nil? || event_type.nil? 
		@event_data = data
	end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def show

  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = env['omniauth.identity']
    if params['show_results']
      @submit_text = 'Show Results'
    else
      @submit_text = 'Register'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_events_helper.rb
module TestEventsHelper
end

app/views/landing_page/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container-fluid">

      <a class="brand" href="" style="padding-top: 0px;"><img src="/assets/tidepool-logo.png" width="100px" ></a>

      <div class="nav-no-collapse header-nav">
        <ul class="nav pull-right">
          <% if current_user && !current_user.guest %>
            <!-- start: User Dropdown -->
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="halflings-icon white user"></i>
                <%= current_user.name %>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="#"><i class="halflings-icon white user"></i> Profile</a></li>
                <li><a href="<%= url_for logout_path %>">
                  <i class="halflings-icon white off"></i>
                  Logout
                </a>
                </li>
              </ul>
            </li>
            <!-- end: User Dropdown -->
          <% else %>
            <%= link_to "Login", login_path, :class => 'login_logout' %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- start: Header -->

app/views/landing_page/show.html.erb
<%= render 'dashboard/layouts/header' %>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2"></div>
    <div class="span7">
      <h1>Awareness is the beginning of improvement</h1>
    </div>
    <div class="span2">
      <button id="getStarted" class="btn btn-large btn-success">Get Started</button>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span1"></div>
    <div class="span5">
      <img src="/assets/landing_page/left.jpeg"/>
    </div>
    <div class="span5">
      <img src="/assets/landing_page/right.jpeg"/>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span1"></div>
    <div class="span1">
      <img src="/assets/landing_page/diego.jpg"/>
    </div>
    <div class="span4">
      <blockquote>
        <p>
          “One of the most exiting ideas I've seen in a while!”
        </p>
        <small>
          Diego Berdakin
        </small>
      </blockquote>
    </div>
    <div class="span1">
      <img src="/assets/landing_page/heather.jpg"/>
    </div>
    <div class="span4">
      <blockquote>
        <p>
          “TidePool has such a smart team tackling a really interesting market. This team is on the money.”
        </p>
        <small>
          Heather Gilchrist
        </small>
      </blockquote>
    </div>
  </div>

  <%= render 'dashboard/layouts/footer' %>
</div>

<%= content_for :javascript do %>
  <%= javascript_include_tag "dashboard/application" %>
  <script>
    $(document).ready(function(){
      $("#getStarted").click(function(){ window.location.href = '/start/2';})
    });
  </script>
<% end %>

<%= content_for :stylesheet do %>
  <!-- start: Mobile Specific -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- end: Mobile Specific -->

  <!-- start: CSS -->
  <%= stylesheet_link_tag "dashboard/application" %>
  <%= stylesheet_link_tag "dashboard/application-responsive" %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,cyrillic-ext,latin-ext' rel='stylesheet' type='text/css'>
  <!-- end: CSS -->

  <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <link id="ie-style" href="/assets/dashboard/ie.css" rel="stylesheet">
  <![endif]-->

  <!--[if IE 9]>
  <link id="ie9style" href="/assets/dashboard/ie9.css" rel="stylesheet">
  <![endif]-->


<% end %>